{
 "title": "hv network",
 "time": { "from": "2022-03-09T22:45:59.000Z", "to": "2022-03-09T23:00:10.000Z" },
 "panels": [
  {
   "title": "ulthar receive",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{hostname=\"ulthar.ds\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "rlyeh receive",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{hostname=\"rlyeh.ds\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "ulthar transmit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{hostname=\"ulthar.ds\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "rlyeh transmit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{hostname=\"rlyeh.ds\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}