{
 "title": "nginx traffic",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "www0x traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({hostname=~`www0\\d\\.ds`,job=\"nginx_access\",status=~\"[123]..\"}[1h])) by (hostname)",
     "legendFormat": "OK reqs/hr"
    },
    {
     "expr": "sum(rate({hostname=~`www0\\d\\.ds`,job=\"nginx_access\",status=~\"4..\"}[1h])) by (hostname)",
     "legendFormat": "4XX reqs/hr"
    },
    {
     "expr": "sum(rate({hostname=~`www0\\d\\.ds`,job=\"nginx_access\",status=~\"5..\"}[1h])) by (hostname)",
     "legendFormat": "5XX reqs/hr"
    }
   ]
  },
  {
   "title": "intranet traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({hostname=~`intranet.ds`,job=\"nginx_access\",status=~\"[123]..\"}[1h])) by (hostname)",
     "legendFormat": "OK reqs/hr"
    },
    {
     "expr": "sum(rate({hostname=~`intranet.ds`,job=\"nginx_access\",status=~\"4..\"}[1h])) by (hostname)",
     "legendFormat": "4XX reqs/hr"
    },
    {
     "expr": "sum(rate({hostname=~`intranet.ds`,job=\"nginx_access\",status=~\"5..\"}[1h])) by (hostname)",
     "legendFormat": "5XX reqs/hr"
    }
   ]
  },
  {
   "title": "www2x traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({hostname=~`www2\\d\\.ds`,job=\"nginx_access\",status=~\"[123]..\"}[1h])) by (hostname)",
     "legendFormat": "OK reqs/hr"
    },
    {
     "expr": "sum(rate({hostname=~`www2\\d\\.ds`,job=\"nginx_access\",status=~\"4..\"}[1h])) by (hostname)",
     "legendFormat": "4XX reqs/hr"
    },
    {
     "expr": "sum(rate({hostname=~`www2\\d\\.ds`,job=\"nginx_access\",status=~\"5..\"}[1h])) by (hostname)",
     "legendFormat": "5XX reqs/hr"
    }
   ]
  }
 ]
}