{
 "title": "Prometheus Monitoring - Node Exporter - System Resources",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(node_uname_info{hostname=~\".*\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "cores",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1-(sum by (cpu) (node_cpu_seconds_total{hostname=\"$hostname\",mode=\"idle\"}))/(sum by (cpu)(node_cpu_seconds_total{hostname=\"$hostname\"}))",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-sum(node_cpu_seconds_total{hostname=\"$hostname\",mode=\"idle\"})/sum(node_cpu_seconds_total{hostname=\"$hostname\"})",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "memory free",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{hostname=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "memory size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{hostname=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{hostname=\"$hostname\"}-node_memory_MemAvailable_bytes{hostname=\"$hostname\"})/node_memory_MemTotal_bytes{hostname=\"$hostname\"}",
     "legendFormat": "RAM usage"
    }
   ]
  },
  {
   "title": "rootfs free",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{hostname=\"$hostname\",mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "rootfs total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{hostname=\"$hostname\",mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-  node_filesystem_avail_bytes{hostname=\"$hostname\",mountpoint=\"/\"}/node_filesystem_size_bytes{hostname=\"$hostname\",mountpoint=\"/\"}",
     "legendFormat": "rootfs used"
    },
    {
     "expr": "1-  node_filesystem_avail_bytes{hostname=\"$hostname\",mountpoint=\"/home\"}/node_filesystem_size_bytes{hostname=\"$hostname\",mountpoint=\"/home\"}",
     "legendFormat": "home used"
    },
    {
     "expr": "1-  node_filesystem_avail_bytes{hostname=\"$hostname\",mountpoint=\"/stor\"}/node_filesystem_size_bytes{hostname=\"$hostname\",mountpoint=\"/stor\"}",
     "legendFormat": "stor used"
    }
   ]
  },
  {
   "title": "active process count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_procs_running {hostname=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(node_network_receive_bytes_total{hostname=\"$hostname\",device=~\"eth0|enp9s0\"}[1m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{hostname=\"$hostname\",device=~\"eth0|enp9s0\"}[1m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "FD allocation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filefd_allocated{hostname=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(node_disk_io_now{hostname=\"$hostname\"})",
     "legendFormat": "IOPS"
    }
   ]
  }
 ]
}