{
 "title": "prometheus-webhosting",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "external", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "external request count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (caddy_http_request_count_total{host=~\"skowron.ski|blog.dsinf.net|foto.dsinf.net\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "external request size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (caddy_http_response_size_bytes_sum{host=~\"^(skowron.ski|blog.dsinf.net|foto.dsinf.net)\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "external request duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (caddy_http_request_duration_seconds_sum{host=~\"^(skowron.ski|blog.dsinf.net|foto.dsinf.net)\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "dbs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "MySQL",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_connections[1m])",
     "legendFormat": "conns/minute"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{ job=\"psql_psql01\"})",
     "legendFormat": "activities"
    }
   ]
  },
  {
   "title": "internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "internal request count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (host) (caddy_http_request_count_total{host!~\"^(skowron.ski|blog.dsinf.net|foto.dsinf.net)\"})",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "internal request size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (host) (caddy_http_response_size_bytes_sum{host!~\"^(skowron.ski|blog.dsinf.net|foto.dsinf.net)\"})",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "internal request duration",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (host) (caddy_http_request_duration_seconds_sum{host!~\"^(skowron.ski|blog.dsinf.net|foto.dsinf.net)\"})",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  }
 ]
}