{
 "title": "Sauron @ Rlyeh",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Rlyeh -> Ulthar External",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "loss",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "rlyeh_ulthar_external",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "rtt",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rlyeh_ulthar_external",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rlyeh -> Ulthar vSwitch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "loss",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "rlyeh_ulthar_vswitch",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "rtt",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rlyeh_ulthar_vswitch",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rlyeh -> Ulthar Private",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "loss",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "rlyeh_ulthar_private",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "rtt",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rlyeh_ulthar_private",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}